name: Deploy to PyPI

on:
  push:
  workflow_dispatch:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  dist:
    name: Build and upload sdist and wheel
    uses: ./.github/workflows/build-distributions.yml

  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: distribution-artifact
          path: dist

      - name: List distributions to be deployed
        run: ls -lha dist/

      # - uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.pypi_password }}
