name: Deploy to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
      - name: Build and upload sdist and wheel
        uses: ./.github/workflows/build-distributions.yml


  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}
